- module-name: 'sketch'
  dlls:
    - from_filenames:
        relative_path: 'libsketch'
        prefixes: 
          - 'libsketch'
        suffixes:
          - 'so'
  anti-bloat:
    - no-follow:
        'PIL': 'ignore'
        'potrace': 'ignore'

